<?php

namespace Tests\Feature\Services;

use App\Helpers\Track;
use App\Models\OauthCredential;
use App\Services\SpotifyService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class SpotifyServiceTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->oac = OauthCredential::factory()->create([
            'provider' => SpotifyService::PROVIDER,
            'user_id'  => $this->user()->getKey(),
        ]);
    }

    public function test_it_maps_playlists_to_playlist_dto()
    {
        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists' . '*' => Http::response([
                "href"     => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k/playlists?offset=0&limit=100",
                "limit"    => 100,
                "next"     => null,
                "offset"   => 0,
                "previous" => null,
                "total"    => 48,
                "items"    => [
                    [
                        "collaborative" => false,
                        "description"   => "",
                        "external_urls" => [
                            "spotify" => "https://open.spotify.com/playlist/35nNzgUrk0HVhGenDAMnaw"
                        ],
                        "href"          => "https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw",
                        "id"            => "35nNzgUrk0HVhGenDAMnaw",
                        "images"        => [
                            [
                                "height" => 640,
                                "url"    => "https://mosaic.scdn.co/640/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 640
                            ],
                            [
                                "height" => 300,
                                "url"    => "https://mosaic.scdn.co/300/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 300
                            ],
                            [
                                "height" => 60,
                                "url"    => "https://mosaic.scdn.co/60/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 60
                            ]
                        ],
                        "name"          => "hyperpop supercut",
                        "owner"         => [
                            "display_name"  => "Ryan",
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                            ],
                            "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                            "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                            "type"          => "user",
                            "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k"
                        ],
                        "primary_color" => null,
                        "public"        => true,
                        "snapshot_id"   => "AAAACFgLXRwUjHxYTp7GYBgQva2fmKBW",
                        "tracks"        => [
                            "href"  => "https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw/tracks",
                            "total" => 12
                        ],
                        "type"          => "playlist",
                        "uri"           => "spotify:playlist:35nNzgUrk0HVhGenDAMnaw"
                    ],
                ]
            ]),
        ]);

        $playlists = (new SpotifyService($this->oac))->getPlaylists();

        $this->assertEquals([[
            'id'               => '35nNzgUrk0HVhGenDAMnaw',
            'name'             => 'hyperpop supercut',
            'tracks'           => 'https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw/tracks',
            'owner'            => [
                'display_name' => 'Ryan',
                'id'           => 'pxd0l8njl07f1wlvhf09zo01k',
            ],
            'number_of_tracks' => 12,
            'image_uri'        => 'https://mosaic.scdn.co/640/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2'
        ]], $playlists);
    }

    public function test_it_maps_playlist_songs_to_song_dto()
    {
        $items = [
            [
                "source"    => "spotify",
                "remote_id" => "spotify:track:0Gz4Q1Bmyef5yA0G6LIIQZ",
                "name"      => "poster boy",
                "artists"   => [
                    "2hollis"
                ],
                "explicit"  => true,
                "album"     => [
                    "id"     => "2cwwBz019F7hQwggBShXCv",
                    "name"   => "2",
                    "images" => [
                        [
                            "height" => 640,
                            "url"    => "https://i.scdn.co/image/ab67616d0000b273057d046c6dfb348e0215567c",
                            "width"  => 640
                        ],
                        [
                            "height" => 300,
                            "url"    => "https://i.scdn.co/image/ab67616d00001e02057d046c6dfb348e0215567c",
                            "width"  => 300
                        ],
                        [
                            "height" => 64,
                            "url"    => "https://i.scdn.co/image/ab67616d00004851057d046c6dfb348e0215567c",
                            "width"  => 64
                        ]
                    ]
                ],
                "meta"      => null
            ],
            [
                "source"    => "spotify",
                "remote_id" => "spotify:track:6C2nVSSeXNqfoY8t6tliZ4",
                "name"      => "jeans",
                "artists"   => [
                    "2hollis"
                ],
                "explicit"  => true,
                "album"     => [
                    "id"     => "7ANu2uI0FVnoQnQsrSiVcO",
                    "name"   => "jeans",
                    "images" => [
                        [
                            "height" => 640,
                            "url"    => "https://i.scdn.co/image/ab67616d0000b273b8362432f72c45d2b6bf08d8",
                            "width"  => 640
                        ],
                        [
                            "height" => 300,
                            "url"    => "https://i.scdn.co/image/ab67616d00001e02b8362432f72c45d2b6bf08d8",
                            "width"  => 300
                        ],
                        [
                            "height" => 64,
                            "url"    => "https://i.scdn.co/image/ab67616d00004851b8362432f72c45d2b6bf08d8",
                            "width"  => 64
                        ]
                    ]
                ],
                "meta"      => null
            ],
            [
                "source"    => "spotify",
                "remote_id" => "spotify:track:0jNhSK5gotdRB1G4nMqEau",
                "name"      => "trauma",
                "artists"   => [
                    "2hollis"
                ],
                "explicit"  => true,
                "album"     => [
                    "id"     => "0eihBhagAmahQQALFmScz3",
                    "name"   => "trauma",
                    "images" => [
                        [
                            "height" => 640,
                            "url"    => "https://i.scdn.co/image/ab67616d0000b273051b22048cf7a4bd3523e6e4",
                            "width"  => 640
                        ],
                        [
                            "height" => 300,
                            "url"    => "https://i.scdn.co/image/ab67616d00001e02051b22048cf7a4bd3523e6e4",
                            "width"  => 300
                        ],
                        [
                            "height" => 64,
                            "url"    => "https://i.scdn.co/image/ab67616d00004851051b22048cf7a4bd3523e6e4",
                            "width"  => 64
                        ]
                    ]
                ],
                "meta"      => null
            ]
        ];
        $payload = [
            'items' => [
                ...$items
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/playlists*' => Http::response($payload),
        ]);

        $playlistTracks = (new SpotifyService($this->oac))->getPlaylistTracks('$playlistId');

        collect($playlistTracks)->each(function ($track, $index) use ($items) {
            $this->assertEquals(SpotifyService::PROVIDER, $track->source);
            $this->assertEquals(Arr::get($items, "$index.track.uri"), $track->remote_id);
            $this->assertEquals(Arr::get($items, "$index.track.name"), $track->name);
            $this->assertEquals(
                collect(Arr::get($items, "$index.track.artists"))
                    ->map(fn($a) => $a['name'])
                    ->toArray(),
                $track->artists
            );
            $this->assertEquals(Arr::get($items, "$index.track.explicit"), $track->explicit);
            $this->assertEquals([
                'id'     => Arr::get($items, "$index.track.album.id"),
                'name'   => Arr::get($items, "$index.track.album.name"),
                'images' => Arr::get($items, "$index.track.album.images"),
            ], $track->album);
        });
    }

    public function test_it_returns_playlist_id_on_successful_creation()
    {
        $expectedPlaylistId = "2wfffynGrerYzxxksZDLUr";
        $response = [
            "collaborative" => false,
            "description"   => "Created via Playlist Transfer",
            "external_urls" => [
                "spotify" => "https://open.spotify.com/playlist/2wfffynGrerYzxxksZDLUr"
            ],
            "followers"     => [
                "href"  => null,
                "total" => 0
            ],
            "href"          => "https://api.spotify.com/v1/playlists/2wfffynGrerYzxxksZDLUr",
            "id"            => $expectedPlaylistId,
            "images"        => [],
            "primary_color" => null,
            "name"          => "tryna test my ghandi",
            "type"          => "playlist",
            "uri"           => "spotify:playlist:2wfffynGrerYzxxksZDLUr",
            "owner"         => [
                "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                "type"          => "user",
                "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k",
                "display_name"  => null,
                "external_urls" => [
                    "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                ]
            ],
            "public"        => false,
            "snapshot_id"   => "AAABbStWDTIJKWT6aEwg5pTMBhBD2m8e",
            "tracks"        => [
                "limit"    => 100,
                "next"     => null,
                "offset"   => 0,
                "previous" => null,
                "href"     => "https://api.spotify.com/v1/playlists/2wfffynGrerYzxxksZDLUr/tracks",
                "total"    => 0,
                "items"    => []
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists*' => Http::response($response),
        ]);

        $actualPlaylistId = (new SpotifyService($this->oac))->createPlaylist('$playlistId');

        $this->assertEquals($expectedPlaylistId, $actualPlaylistId);
    }

    public function test_it_returns_false_if_playlist_creation_fails()
    {
        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists*' => Http::response([], 422),
        ]);

        $actualPlaylistId = (new SpotifyService($this->oac))->createPlaylist('$playlistId');

        $this->assertFalse($actualPlaylistId);
    }

    public function test_it_maps_search_results_to_song_dto()
    {
        $items = [
            [
                "album"         => [
                    "album_type"             => "album",
                    "artists"                => [
                        [
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/artist/4kqFrZkeqDfOIEqTWqbOOV"
                            ],
                            "href"          => "https://api.spotify.com/v1/artists/4kqFrZkeqDfOIEqTWqbOOV",
                            "id"            => "4kqFrZkeqDfOIEqTWqbOOV",
                            "name"          => "brakence",
                            "type"          => "artist",
                            "uri"           => "spotify:artist:4kqFrZkeqDfOIEqTWqbOOV"
                        ]
                    ],
                    "external_urls"          => [
                        "spotify" => "https://open.spotify.com/album/6XV76W17coHAKFdeyiGT08"
                    ],
                    "href"                   => "https://api.spotify.com/v1/albums/6XV76W17coHAKFdeyiGT08",
                    "id"                     => "6XV76W17coHAKFdeyiGT08",
                    "images"                 => [
                        [
                            "height" => 640,
                            "width"  => 640,
                            "url"    => "https://i.scdn.co/image/ab67616d0000b273cbf54392eca47bb30303db4c"
                        ],
                        [
                            "height" => 300,
                            "width"  => 300,
                            "url"    => "https://i.scdn.co/image/ab67616d00001e02cbf54392eca47bb30303db4c"
                        ],
                        [
                            "height" => 64,
                            "width"  => 64,
                            "url"    => "https://i.scdn.co/image/ab67616d00004851cbf54392eca47bb30303db4c"
                        ]
                    ],
                    "is_playable"            => true,
                    "name"                   => "hypochondriac",
                    "release_date"           => "2022-12-02",
                    "release_date_precision" => "day",
                    "total_tracks"           => 13,
                    "type"                   => "album",
                    "uri"                    => "spotify:album:6XV76W17coHAKFdeyiGT08"
                ],
                "artists"       => [
                    [
                        "external_urls" => [
                            "spotify" => "https://open.spotify.com/artist/4kqFrZkeqDfOIEqTWqbOOV"
                        ],
                        "href"          => "https://api.spotify.com/v1/artists/4kqFrZkeqDfOIEqTWqbOOV",
                        "id"            => "4kqFrZkeqDfOIEqTWqbOOV",
                        "name"          => "brakence",
                        "type"          => "artist",
                        "uri"           => "spotify:artist:4kqFrZkeqDfOIEqTWqbOOV"
                    ]
                ],
                "disc_number"   => 1,
                "duration_ms"   => 209706,
                "explicit"      => true,
                "external_ids"  => [
                    "isrc" => "USSM12210309"
                ],
                "external_urls" => [
                    "spotify" => "https://open.spotify.com/track/61Ph6Q4HYgWUVGulPszt9n"
                ],
                "href"          => "https://api.spotify.com/v1/tracks/61Ph6Q4HYgWUVGulPszt9n",
                "id"            => "61Ph6Q4HYgWUVGulPszt9n",
                "is_local"      => false,
                "is_playable"   => true,
                "name"          => "5g",
                "popularity"    => 54,
                "preview_url"   => null,
                "track_number"  => 6,
                "type"          => "track",
                "uri"           => "spotify:track:61Ph6Q4HYgWUVGulPszt9n"
            ]
        ];
        $response = [
            "tracks" => [
                "href"     => "https://api.spotify.com/v1/search?offset=0&limit=1&query=brakence%205G&type=track",
                "limit"    => 1,
                "next"     => "https://api.spotify.com/v1/search?offset=1&limit=1&query=brakence%205G&type=track",
                "offset"   => 0,
                "previous" => null,
                "total"    => 807,
                "items"    => $items
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/search*' => Http::response($response),
            '*'                                   => Http::response([])
        ]);

        $actual = (new SpotifyService($this->oac))->searchTrack(new Track(['artists' => ['brakence']]));

        $this->assertCount(1, $actual);

        $track = $actual[0];

        $this->assertEquals(SpotifyService::PROVIDER, $track->source);
        $this->assertEquals(Arr::get($items, "0.uri"), $track->remote_id);
        $this->assertEquals(Arr::get($items, "0.name"), $track->name);
        $this->assertEquals(
            collect(Arr::get($items, "0.artists"))
                ->map(fn($a) => $a['name'])
                ->toArray(),
            $track->artists
        );
        $this->assertEquals(Arr::get($items, "0.explicit"), $track->explicit);
        $this->assertEquals([
            'id'     => Arr::get($items, "0.album.id"),
            'name'   => Arr::get($items, "0.album.name"),
            'images' => Arr::get($items, "0.album.images"),
        ], $track->album);
    }

    public function test_it_returns_true_if_track_added_to_playlist()
    {
        Http::fake(['*' => Http::response()]);

        $actual = (new SpotifyService($this->oac))->addTrackToPlaylist('123', new Track(['artists' => ['brakence']]));

        $this->assertTrue($actual);
    }

    public function test_it_returns_false_if_track_not_added_to_playlist()
    {
        Http::fake(['*' => Http::response([], 422)]);

        $actual = (new SpotifyService($this->oac))->addTrackToPlaylist('123', new Track(['artists' => ['brakence']]));

        $this->assertFalse($actual);
    }
}
