<?php

namespace Tests\Feature\Services;

use App\Helpers\Track;
use App\Models\OauthCredential;
use App\Services\SpotifyService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class SpotifyServiceTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->oac = OauthCredential::factory()->create([
            'provider' => SpotifyService::PROVIDER,
            'user_id'  => $this->user()->getKey(),
        ]);
    }

    public function test_it_maps_playlists_to_playlist_dto()
    {
        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists' . '*' => Http::response([
                "href"     => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k/playlists?offset=0&limit=100",
                "limit"    => 100,
                "next"     => null,
                "offset"   => 0,
                "previous" => null,
                "total"    => 48,
                "items"    => [
                    [
                        "collaborative" => false,
                        "description"   => "",
                        "external_urls" => [
                            "spotify" => "https://open.spotify.com/playlist/35nNzgUrk0HVhGenDAMnaw"
                        ],
                        "href"          => "https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw",
                        "id"            => "35nNzgUrk0HVhGenDAMnaw",
                        "images"        => [
                            [
                                "height" => 640,
                                "url"    => "https://mosaic.scdn.co/640/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 640
                            ],
                            [
                                "height" => 300,
                                "url"    => "https://mosaic.scdn.co/300/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 300
                            ],
                            [
                                "height" => 60,
                                "url"    => "https://mosaic.scdn.co/60/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2",
                                "width"  => 60
                            ]
                        ],
                        "name"          => "hyperpop supercut",
                        "owner"         => [
                            "display_name"  => "Ryan",
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                            ],
                            "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                            "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                            "type"          => "user",
                            "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k"
                        ],
                        "primary_color" => null,
                        "public"        => true,
                        "snapshot_id"   => "AAAACFgLXRwUjHxYTp7GYBgQva2fmKBW",
                        "tracks"        => [
                            "href"  => "https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw/tracks",
                            "total" => 12
                        ],
                        "type"          => "playlist",
                        "uri"           => "spotify:playlist:35nNzgUrk0HVhGenDAMnaw"
                    ],
                ]
            ]),
        ]);

        $playlists = (new SpotifyService($this->oac))->getPlaylists();

        $this->assertEquals([[
            'id'               => '35nNzgUrk0HVhGenDAMnaw',
            'name'             => 'hyperpop supercut',
            'tracks'           => 'https://api.spotify.com/v1/playlists/35nNzgUrk0HVhGenDAMnaw/tracks',
            'owner'            => [
                'display_name' => 'Ryan',
                'id'           => 'pxd0l8njl07f1wlvhf09zo01k',
            ],
            'number_of_tracks' => 12,
            'image_uri'        => 'https://mosaic.scdn.co/640/ab67616d00001e02051b22048cf7a4bd3523e6e4ab67616d00001e02057d046c6dfb348e0215567cab67616d00001e02b8362432f72c45d2b6bf08d8ab67616d00001e02edb4ce20d2432cad4ddfcaa2'
        ]], $playlists);
    }

    public function test_it_maps_playlist_songs_to_song_dto()
    {
        $items = [
            [
                "added_at"        => "2023-08-12T19:14:59Z",
                "added_by"        => [
                    "external_urls" => [
                        "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                    ],
                    "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                    "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                    "type"          => "user",
                    "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k"
                ],
                "is_local"        => false,
                "primary_color"   => null,
                "track"           => [
                    "preview_url"       => null,
                    "available_markets" => [],
                    "explicit"          => false,
                    "type"              => "track",
                    "episode"           => false,
                    "track"             => true,
                    "album"             => [
                        "available_markets"      => [],
                        "type"                   => "album",
                        "album_type"             => "single",
                        "href"                   => "https://api.spotify.com/v1/albums/0FawTVuFbmS9KLWA8TAtau",
                        "id"                     => "0FawTVuFbmS9KLWA8TAtau",
                        "images"                 => [
                            [
                                "height" => 640,
                                "url"    => "https://i.scdn.co/image/ab67616d0000b2736758b0ff4e8745ca7386921f",
                                "width"  => 640
                            ],
                            [
                                "height" => 300,
                                "url"    => "https://i.scdn.co/image/ab67616d00001e026758b0ff4e8745ca7386921f",
                                "width"  => 300
                            ],
                            [
                                "height" => 64,
                                "url"    => "https://i.scdn.co/image/ab67616d000048516758b0ff4e8745ca7386921f",
                                "width"  => 64
                            ]
                        ],
                        "name"                   => "Six Forty Seven",
                        "release_date"           => "2016-03-28",
                        "release_date_precision" => "day",
                        "uri"                    => "spotify:album:0FawTVuFbmS9KLWA8TAtau",
                        "artists"                => [
                            [
                                "external_urls" => [
                                    "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                                ],
                                "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                                "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                                "name"          => "Instupendo",
                                "type"          => "artist",
                                "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                            ]
                        ],
                        "external_urls"          => [
                            "spotify" => "https://open.spotify.com/album/0FawTVuFbmS9KLWA8TAtau"
                        ],
                        "total_tracks"           => 1
                    ],
                    "artists"           => [
                        [
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                            ],
                            "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                            "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                            "name"          => "Instupendo",
                            "type"          => "artist",
                            "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                        ]
                    ],
                    "disc_number"       => 1,
                    "track_number"      => 1,
                    "duration_ms"       => 119990,
                    "external_ids"      => [
                        "isrc" => "QM4DW1618349"
                    ],
                    "external_urls"     => [
                        "spotify" => "https://open.spotify.com/track/2WuK1opHQzRo18YXCtY2DF"
                    ],
                    "href"              => "https://api.spotify.com/v1/tracks/2WuK1opHQzRo18YXCtY2DF",
                    "id"                => "2WuK1opHQzRo18YXCtY2DF",
                    "name"              => "Six Forty Seven",
                    "popularity"        => 2,
                    "uri"               => "spotify:track:2WuK1opHQzRo18YXCtY2DF",
                    "is_local"          => false
                ],
                "video_thumbnail" => [
                    "url" => null
                ]
            ],
            [
                "added_at"        => "2023-08-12T19:15:02Z",
                "added_by"        => [
                    "external_urls" => [
                        "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                    ],
                    "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                    "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                    "type"          => "user",
                    "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k"
                ],
                "is_local"        => false,
                "primary_color"   => null,
                "track"           => [
                    "preview_url"       => null,
                    "explicit"          => false,
                    "type"              => "track",
                    "episode"           => false,
                    "track"             => true,
                    "album"             => [
                        "type"                   => "album",
                        "album_type"             => "single",
                        "href"                   => "https://api.spotify.com/v1/albums/01qVg4PWWaeremZOHDVRS1",
                        "id"                     => "01qVg4PWWaeremZOHDVRS1",
                        "images"                 => [
                            [
                                "height" => 640,
                                "url"    => "https://i.scdn.co/image/ab67616d0000b2734a41ed550aa0d6566e43b3f2",
                                "width"  => 640
                            ],
                            [
                                "height" => 300,
                                "url"    => "https://i.scdn.co/image/ab67616d00001e024a41ed550aa0d6566e43b3f2",
                                "width"  => 300
                            ],
                            [
                                "height" => 64,
                                "url"    => "https://i.scdn.co/image/ab67616d000048514a41ed550aa0d6566e43b3f2",
                                "width"  => 64
                            ]
                        ],
                        "name"                   => "Comfort Chain",
                        "release_date"           => "2017-01-20",
                        "release_date_precision" => "day",
                        "uri"                    => "spotify:album:01qVg4PWWaeremZOHDVRS1",
                        "artists"                => [
                            [
                                "external_urls" => [
                                    "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                                ],
                                "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                                "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                                "name"          => "Instupendo",
                                "type"          => "artist",
                                "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                            ]
                        ],
                        "external_urls"          => [
                            "spotify" => "https://open.spotify.com/album/01qVg4PWWaeremZOHDVRS1"
                        ],
                        "total_tracks"           => 1
                    ],
                    "artists"           => [
                        [
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                            ],
                            "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                            "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                            "name"          => "Instupendo",
                            "type"          => "artist",
                            "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                        ]
                    ],
                    "disc_number"       => 1,
                    "track_number"      => 1,
                    "duration_ms"       => 184363,
                    "external_ids"      => [
                        "isrc" => "QZ5D71600005"
                    ],
                    "external_urls"     => [
                        "spotify" => "https://open.spotify.com/track/0Db8f7uikjXxH3qHe0UKoW"
                    ],
                    "href"              => "https://api.spotify.com/v1/tracks/0Db8f7uikjXxH3qHe0UKoW",
                    "id"                => "0Db8f7uikjXxH3qHe0UKoW",
                    "name"              => "Comfort Chain",
                    "popularity"        => 73,
                    "uri"               => "spotify:track:0Db8f7uikjXxH3qHe0UKoW",
                    "is_local"          => false
                ],
                "video_thumbnail" => [
                    "url" => null
                ]
            ],
            [
                "added_at"        => "2023-08-12T19:15:04Z",
                "added_by"        => [
                    "external_urls" => [
                        "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                    ],
                    "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                    "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                    "type"          => "user",
                    "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k"
                ],
                "is_local"        => false,
                "primary_color"   => null,
                "track"           => [
                    "preview_url"       => null,
                    "explicit"          => false,
                    "type"              => "track",
                    "episode"           => false,
                    "track"             => true,
                    "album"             => [
                        "type"                   => "album",
                        "album_type"             => "single",
                        "href"                   => "https://api.spotify.com/v1/albums/3PQQmgHwmrt6Eta9eI8zjt",
                        "id"                     => "3PQQmgHwmrt6Eta9eI8zjt",
                        "images"                 => [
                            [
                                "height" => 640,
                                "url"    => "https://i.scdn.co/image/ab67616d0000b2731bdf6d45aaa8a7cee6c88c9c",
                                "width"  => 640
                            ],
                            [
                                "height" => 300,
                                "url"    => "https://i.scdn.co/image/ab67616d00001e021bdf6d45aaa8a7cee6c88c9c",
                                "width"  => 300
                            ],
                            [
                                "height" => 64,
                                "url"    => "https://i.scdn.co/image/ab67616d000048511bdf6d45aaa8a7cee6c88c9c",
                                "width"  => 64
                            ]
                        ],
                        "name"                   => "Falling",
                        "release_date"           => "2016-09-16",
                        "release_date_precision" => "day",
                        "uri"                    => "spotify:album:3PQQmgHwmrt6Eta9eI8zjt",
                        "artists"                => [
                            [
                                "external_urls" => [
                                    "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                                ],
                                "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                                "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                                "name"          => "Instupendo",
                                "type"          => "artist",
                                "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                            ]
                        ],
                        "external_urls"          => [
                            "spotify" => "https://open.spotify.com/album/3PQQmgHwmrt6Eta9eI8zjt"
                        ],
                        "total_tracks"           => 1
                    ],
                    "artists"           => [
                        [
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/artist/3ctnkEZGtVBTxS7IMin8nC"
                            ],
                            "href"          => "https://api.spotify.com/v1/artists/3ctnkEZGtVBTxS7IMin8nC",
                            "id"            => "3ctnkEZGtVBTxS7IMin8nC",
                            "name"          => "Instupendo",
                            "type"          => "artist",
                            "uri"           => "spotify:artist:3ctnkEZGtVBTxS7IMin8nC"
                        ]
                    ],
                    "disc_number"       => 1,
                    "track_number"      => 1,
                    "duration_ms"       => 119744,
                    "external_ids"      => [
                        "isrc" => "UST8K1628643"
                    ],
                    "external_urls"     => [
                        "spotify" => "https://open.spotify.com/track/5tG9KCkEnWc75cREtb4ffB"
                    ],
                    "href"              => "https://api.spotify.com/v1/tracks/5tG9KCkEnWc75cREtb4ffB",
                    "id"                => "5tG9KCkEnWc75cREtb4ffB",
                    "name"              => "Falling",
                    "popularity"        => 60,
                    "uri"               => "spotify:track:5tG9KCkEnWc75cREtb4ffB",
                    "is_local"          => false
                ],
                "video_thumbnail" => [
                    "url" => null
                ]
            ],
        ];
        $payload = [
            'items' => [
                ...$items
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/playlists*' => Http::response($payload),
        ]);

        $playlistTracks = (new SpotifyService($this->oac))->getPlaylistTracks('$playlistId');

        collect($playlistTracks)->each(function ($track, $index) use ($items) {
            $this->assertEquals(SpotifyService::PROVIDER, $track->source);
            $this->assertEquals(Arr::get($items, "$index.track.uri"), $track->remote_id);
            $this->assertEquals(Arr::get($items, "$index.track.external_ids.isrc"), $track->isrc);
            $this->assertEquals(Arr::get($items, "$index.track.name"), $track->name);
            $this->assertEquals(Arr::get($items, "$index.track.name"), $track->name);
            $this->assertEquals(
                collect(Arr::get($items, "$index.track.artists"))
                    ->map(fn($a) => $a['name'])
                    ->toArray(),
                $track->artists
            );
            $this->assertEquals(Arr::get($items, "$index.track.explicit"), $track->explicit);
            $this->assertEquals([
                'id'     => Arr::get($items, "$index.track.album.id"),
                'name'   => Arr::get($items, "$index.track.album.name"),
                'images' => Arr::get($items, "$index.track.album.images"),
            ], $track->album);
        });
    }

    public function test_it_returns_playlist_id_on_successful_creation()
    {
        $expectedPlaylistId = "2wfffynGrerYzxxksZDLUr";
        $response = [
            "collaborative" => false,
            "description"   => "Created via Playlist Transfer",
            "external_urls" => [
                "spotify" => "https://open.spotify.com/playlist/2wfffynGrerYzxxksZDLUr"
            ],
            "followers"     => [
                "href"  => null,
                "total" => 0
            ],
            "href"          => "https://api.spotify.com/v1/playlists/2wfffynGrerYzxxksZDLUr",
            "id"            => $expectedPlaylistId,
            "images"        => [],
            "primary_color" => null,
            "name"          => "tryna test my ghandi",
            "type"          => "playlist",
            "uri"           => "spotify:playlist:2wfffynGrerYzxxksZDLUr",
            "owner"         => [
                "href"          => "https://api.spotify.com/v1/users/pxd0l8njl07f1wlvhf09zo01k",
                "id"            => "pxd0l8njl07f1wlvhf09zo01k",
                "type"          => "user",
                "uri"           => "spotify:user:pxd0l8njl07f1wlvhf09zo01k",
                "display_name"  => null,
                "external_urls" => [
                    "spotify" => "https://open.spotify.com/user/pxd0l8njl07f1wlvhf09zo01k"
                ]
            ],
            "public"        => false,
            "snapshot_id"   => "AAABbStWDTIJKWT6aEwg5pTMBhBD2m8e",
            "tracks"        => [
                "limit"    => 100,
                "next"     => null,
                "offset"   => 0,
                "previous" => null,
                "href"     => "https://api.spotify.com/v1/playlists/2wfffynGrerYzxxksZDLUr/tracks",
                "total"    => 0,
                "items"    => []
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists*' => Http::response($response),
        ]);

        $actualPlaylistId = (new SpotifyService($this->oac))->createPlaylist('$playlistId');

        $this->assertEquals($expectedPlaylistId, $actualPlaylistId);
    }

    public function test_it_returns_false_if_playlist_creation_fails()
    {
        Http::fake([
            SpotifyService::BASE_URL . '/me/playlists*' => Http::response([], 422),
        ]);

        $actualPlaylistId = (new SpotifyService($this->oac))->createPlaylist('$playlistId');

        $this->assertFalse($actualPlaylistId);
    }

    public function test_it_maps_search_results_to_song_dto()
    {
        $items = [
            [
                "album"         => [
                    "album_type"             => "album",
                    "artists"                => [
                        [
                            "external_urls" => [
                                "spotify" => "https://open.spotify.com/artist/4kqFrZkeqDfOIEqTWqbOOV"
                            ],
                            "href"          => "https://api.spotify.com/v1/artists/4kqFrZkeqDfOIEqTWqbOOV",
                            "id"            => "4kqFrZkeqDfOIEqTWqbOOV",
                            "name"          => "brakence",
                            "type"          => "artist",
                            "uri"           => "spotify:artist:4kqFrZkeqDfOIEqTWqbOOV"
                        ]
                    ],
                    "external_urls"          => [
                        "spotify" => "https://open.spotify.com/album/6XV76W17coHAKFdeyiGT08"
                    ],
                    "href"                   => "https://api.spotify.com/v1/albums/6XV76W17coHAKFdeyiGT08",
                    "id"                     => "6XV76W17coHAKFdeyiGT08",
                    "images"                 => [
                        [
                            "height" => 640,
                            "width"  => 640,
                            "url"    => "https://i.scdn.co/image/ab67616d0000b273cbf54392eca47bb30303db4c"
                        ],
                        [
                            "height" => 300,
                            "width"  => 300,
                            "url"    => "https://i.scdn.co/image/ab67616d00001e02cbf54392eca47bb30303db4c"
                        ],
                        [
                            "height" => 64,
                            "width"  => 64,
                            "url"    => "https://i.scdn.co/image/ab67616d00004851cbf54392eca47bb30303db4c"
                        ]
                    ],
                    "is_playable"            => true,
                    "name"                   => "hypochondriac",
                    "release_date"           => "2022-12-02",
                    "release_date_precision" => "day",
                    "total_tracks"           => 13,
                    "type"                   => "album",
                    "uri"                    => "spotify:album:6XV76W17coHAKFdeyiGT08"
                ],
                "artists"       => [
                    [
                        "external_urls" => [
                            "spotify" => "https://open.spotify.com/artist/4kqFrZkeqDfOIEqTWqbOOV"
                        ],
                        "href"          => "https://api.spotify.com/v1/artists/4kqFrZkeqDfOIEqTWqbOOV",
                        "id"            => "4kqFrZkeqDfOIEqTWqbOOV",
                        "name"          => "brakence",
                        "type"          => "artist",
                        "uri"           => "spotify:artist:4kqFrZkeqDfOIEqTWqbOOV"
                    ]
                ],
                "disc_number"   => 1,
                "duration_ms"   => 209706,
                "explicit"      => true,
                "external_ids"  => [
                    "isrc" => "USSM12210309"
                ],
                "external_urls" => [
                    "spotify" => "https://open.spotify.com/track/61Ph6Q4HYgWUVGulPszt9n"
                ],
                "href"          => "https://api.spotify.com/v1/tracks/61Ph6Q4HYgWUVGulPszt9n",
                "id"            => "61Ph6Q4HYgWUVGulPszt9n",
                "is_local"      => false,
                "is_playable"   => true,
                "name"          => "5g",
                "popularity"    => 54,
                "preview_url"   => null,
                "track_number"  => 6,
                "type"          => "track",
                "uri"           => "spotify:track:61Ph6Q4HYgWUVGulPszt9n"
            ]
        ];
        $response = [
            "tracks" => [
                "href"     => "https://api.spotify.com/v1/search?offset=0&limit=1&query=brakence%205G&type=track",
                "limit"    => 1,
                "next"     => "https://api.spotify.com/v1/search?offset=1&limit=1&query=brakence%205G&type=track",
                "offset"   => 0,
                "previous" => null,
                "total"    => 807,
                "items"    => $items
            ]
        ];

        Http::fake([
            SpotifyService::BASE_URL . '/search*' => Http::response($response),
            '*'                                   => Http::response([])
        ]);

        $actual = (new SpotifyService($this->oac))->searchTrack(new Track(['artists' => ['brakence']]));

        $this->assertCount(1, $actual);

        $track = $actual[0];

        $this->assertEquals(SpotifyService::PROVIDER, $track->source);
        $this->assertEquals(Arr::get($items, "0.uri"), $track->remote_id);
        $this->assertEquals(Arr::get($items, "0.external_ids.isrc"), $track->isrc);
        $this->assertEquals(Arr::get($items, "0.name"), $track->name);
        $this->assertEquals(
            collect(Arr::get($items, "0.artists"))
                ->map(fn($a) => $a['name'])
                ->toArray(),
            $track->artists
        );
        $this->assertEquals(Arr::get($items, "0.explicit"), $track->explicit);
        $this->assertEquals([
            'id'     => Arr::get($items, "0.album.id"),
            'name'   => Arr::get($items, "0.album.name"),
            'images' => Arr::get($items, "0.album.images"),
        ], $track->album);
    }

    public function test_it_returns_true_if_track_added_to_playlist()
    {
        Http::fake(['*' => Http::response()]);

        $actual = (new SpotifyService($this->oac))->addTrackToPlaylist('123', new Track(['artists' => ['brakence']]));

        $this->assertTrue($actual);
    }

    public function test_it_returns_false_if_track_not_added_to_playlist()
    {
        Http::fake(['*' => Http::response([], 422)]);

        $actual = (new SpotifyService($this->oac))->addTrackToPlaylist('123', new Track(['artists' => ['brakence']]));

        $this->assertFalse($actual);
    }
}
