<?php

namespace Tests\Feature\Services;

use App\Helpers\Track;
use App\Models\OauthCredential;
use App\Services\SpotifyService;
use App\Services\TidalService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class TidalServiceTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->oac = OauthCredential::factory()->create([
            'provider' => TidalService::PROVIDER,
            'user_id'  => $this->user()->getKey(),
        ]);
    }

    public function test_it_maps_playlists_to_playlist_dto()
    {
        Http::fake([
            TidalService::BASE_URL . '/playlists*' => Http::response([
                "data"  => [
                    [
                        "id"            => "8f95326f-17c8-4c1d-bbd8-9364df0cad7b",
                        "type"          => "playlists",
                        "attributes"    => [
                            "name"           => "NEW YORK CITY SPECIFIC MUSIC",
                            "description"    => "",
                            "bounded"        => true,
                            "duration"       => "PT9M9S",
                            "numberOfItems"  => 2,
                            "externalLinks"  => [
                                [
                                    "href" => "https://listen.tidal.com/playlist/8f95326f-17c8-4c1d-bbd8-9364df0cad7b",
                                    "meta" => [
                                        "type" => "TIDAL_SHARING"
                                    ]
                                ],
                                [
                                    "href" => "https://tidal.com/playlist/8f95326f-17c8-4c1d-bbd8-9364df0cad7b?play=true",
                                    "meta" => [
                                        "type" => "TIDAL_AUTOPLAY_ANDROID"
                                    ]
                                ],
                                [
                                    "href" => "https://tidal.com/playlist/8f95326f-17c8-4c1d-bbd8-9364df0cad7b?play=true",
                                    "meta" => [
                                        "type" => "TIDAL_AUTOPLAY_IOS"
                                    ]
                                ],
                                [
                                    "href" => "https://listen.tidal.com/playlist/8f95326f-17c8-4c1d-bbd8-9364df0cad7b?play=true",
                                    "meta" => [
                                        "type" => "TIDAL_AUTOPLAY_WEB"
                                    ]
                                ]
                            ],
                            "createdAt"      => "2025-11-29T22:10:01.476Z",
                            "lastModifiedAt" => "2025-11-29T22:10:18.057Z",
                            "accessType"     => "UNLISTED",
                            "playlistType"   => "USER"
                        ],
                        "relationships" => [
                            "coverArt" => [
                                "links" => [
                                    "self" => "/playlists/8f95326f-17c8-4c1d-bbd8-9364df0cad7b/relationships/coverArt?countryCode=CA"
                                ]
                            ],
                            "items"    => [
                                "links" => [
                                    "self" => "/playlists/8f95326f-17c8-4c1d-bbd8-9364df0cad7b/relationships/items?countryCode=CA"
                                ]
                            ],
                            "owners"   => [
                                "links" => [
                                    "self" => "/playlists/8f95326f-17c8-4c1d-bbd8-9364df0cad7b/relationships/owners?countryCode=CA"
                                ]
                            ]
                        ]
                    ]
                ],
                "links" => [
                    "self" => "/playlists?filter%5Bowners.id%5D=204091075&countryCode=CA",
                    "next" => "/playlists?filter%5Bowners.id%5D=204091075&countryCode=CA&page%5Bcursor%5D=eyJpZCI6IjUzYzliM2M4LWU0ZDYtNDQyMC05YTk4LTgyNzg2NzNhNGQxZSIsIm5hbWUiOiJzbmlja2VycyIsImFkZGVkQXQiOiIyMDI1LTExLTI5VDIxOjEyOjA3LjY4ODMwOVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTI5VDIxOjEyOjA3LjY4ODMwOVoiLCJpdGVtVHlwZSI6IlVTRVJfUExBWUxJU1QiLCJhcnRpc3ROYW1lIjpudWxsLCJyZWxlYXNlZEF0IjpudWxsLCJtaXhUeXBlIjpudWxsfQ%3D%3D",
                    "meta" => [
                        "nextCursor" => "eyJpZCI6IjUzYzliM2M4LWU0ZDYtNDQyMC05YTk4LTgyNzg2NzNhNGQxZSIsIm5hbWUiOiJzbmlja2VycyIsImFkZGVkQXQiOiIyMDI1LTExLTI5VDIxOjEyOjA3LjY4ODMwOVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTI5VDIxOjEyOjA3LjY4ODMwOVoiLCJpdGVtVHlwZSI6IlVTRVJfUExBWUxJU1QiLCJhcnRpc3ROYW1lIjpudWxsLCJyZWxlYXNlZEF0IjpudWxsLCJtaXhUeXBlIjpudWxsfQ=="
                    ]
                ]
            ]),
        ]);

        $actual = (new TidalService($this->oac))->getPlaylists();

        $this->assertEquals([[
            'id'               => '8f95326f-17c8-4c1d-bbd8-9364df0cad7b',
            'name'             => 'NEW YORK CITY SPECIFIC MUSIC',
            'tracks'           => [],
            'owner'            => [
                'display_name' => '',
            ],
            'number_of_tracks' => 2,
            'image_uri'        => null
        ]], $actual);
    }

    public function test_it_maps_playlist_songs_to_song_dto()
    {
        $trackOne = [
            "data"  => [
                "id"            => "37704290",
                "type"          => "tracks",
                "attributes"    => [
                    "title"         => "Empire State Of Mind",
                    "version"       => null,
                    "isrc"          => "USJZ10900031",
                    "duration"      => "PT4M37S",
                    "copyright"     => [
                        "text" => "\u2117 2009 S. Carter Enterprises, LLC., Distributed by Roc Nation"
                    ],
                    "explicit"      => true,
                    "popularity"    => 0.9216232727726562,
                    "accessType"    => "PUBLIC",
                    "availability"  => [
                        "STREAM",
                        "DJ"
                    ],
                    "mediaTags"     => [
                        "LOSSLESS"
                    ],
                    "externalLinks" => [
                        [
                            "href" => "https://tidal.com/browse/track/37704290",
                            "meta" => [
                                "type" => "TIDAL_SHARING"
                            ]
                        ]
                    ],
                    "spotlighted"   => false,
                    "createdAt"     => "2014-11-07T02:18:24Z"
                ],
                "relationships" => [
                    "albums"          => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/albums"
                        ]
                    ],
                    "artists"         => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/artists"
                        ]
                    ],
                    "genres"          => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/genres"
                        ]
                    ],
                    "lyrics"          => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/lyrics"
                        ]
                    ],
                    "owners"          => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/owners"
                        ]
                    ],
                    "providers"       => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/providers"
                        ]
                    ],
                    "radio"           => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/radio"
                        ]
                    ],
                    "shares"          => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/shares"
                        ]
                    ],
                    "similarTracks"   => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/similarTracks"
                        ]
                    ],
                    "sourceFile"      => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/sourceFile"
                        ]
                    ],
                    "trackStatistics" => [
                        "links" => [
                            "self" => "/tracks/37704290/relationships/trackStatistics"
                        ]
                    ]
                ]
            ],
            "links" => [
                "self" => "/tracks/37704290"
            ]
        ];
        $trackArtistsOne = [
            "data"  => [
                ["id" => "7804", "type" => "artists"],
                ["id" => "1552", "type" => "artists"]],
            "links" => ["self" => "/tracks/37704290/relationships/artists"
            ]
        ];
        $artistOne = [
            "data"  => [
                "id"            => "7804",
                "type"          => "artists",
                "attributes"    => [
                    "name"          => "JAY Z",
                    "popularity"    => 0.9614253085579615,
                    "externalLinks" => [
                        [
                            "href" => "https://www.facebook.com/JayZ",
                            "meta" => [
                                "type" => "FACEBOOK"
                            ]
                        ],
                        [
                            "href" => "https://twitter.com/SC",
                            "meta" => [
                                "type" => "TWITTER"
                            ]
                        ],
                        [
                            "href" => "https://tidal.com/browse/artist/7804",
                            "meta" => [
                                "type" => "TIDAL_SHARING"
                            ]
                        ]
                    ]
                ],
                "relationships" => [
                    "albums"         => [
                        "links" => [
                            "self" => "/artists/7804/relationships/albums"
                        ]
                    ],
                    "biography"      => [
                        "links" => [
                            "self" => "/artists/7804/relationships/biography"
                        ]
                    ],
                    "followers"      => [
                        "links" => [
                            "self" => "/artists/7804/relationships/followers"
                        ]
                    ],
                    "following"      => [
                        "links" => [
                            "self" => "/artists/7804/relationships/following"
                        ]
                    ],
                    "owners"         => [
                        "links" => [
                            "self" => "/artists/7804/relationships/owners"
                        ]
                    ],
                    "profileArt"     => [
                        "links" => [
                            "self" => "/artists/7804/relationships/profileArt"
                        ]
                    ],
                    "radio"          => [
                        "links" => [
                            "self" => "/artists/7804/relationships/radio"
                        ]
                    ],
                    "roles"          => [
                        "links" => [
                            "self" => "/artists/7804/relationships/roles"
                        ]
                    ],
                    "similarArtists" => [
                        "links" => [
                            "self" => "/artists/7804/relationships/similarArtists"
                        ]
                    ],
                    "trackProviders" => [
                        "links" => [
                            "self" => "/artists/7804/relationships/trackProviders"
                        ]
                    ],
                    "tracks"         => [
                        "links" => [
                            "self" => "/artists/7804/relationships/tracks"
                        ]
                    ],
                    "videos"         => [
                        "links" => [
                            "self" => "/artists/7804/relationships/videos"
                        ]
                    ]
                ]
            ],
            "links" => [
                "self" => "/artists/7804"
            ]
        ];
        $songTwo = [
            "data"  => [
                "id"            => "151799532",
                "type"          => "tracks",
                "attributes"    => [
                    "title"         => "New York Times",
                    "version"       => null,
                    "isrc"          => "USQX91301194",
                    "duration"      => "PT4M32S",
                    "copyright"     => [
                        "text" => "\u2117 2013 Cole World/Interscope Records"
                    ],
                    "explicit"      => true,
                    "popularity"    => 0.58152275901143,
                    "accessType"    => "PUBLIC",
                    "availability"  => [
                        "STREAM",
                        "DJ"
                    ],
                    "mediaTags"     => [
                        "LOSSLESS"
                    ],
                    "externalLinks" => [
                        [
                            "href" => "https://tidal.com/browse/track/151799532",
                            "meta" => [
                                "type" => "TIDAL_SHARING"
                            ]
                        ]
                    ],
                    "spotlighted"   => false
                ],
                "relationships" => [
                    "albums"          => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/albums"
                        ]
                    ],
                    "artists"         => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/artists"
                        ]
                    ],
                    "genres"          => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/genres"
                        ]
                    ],
                    "lyrics"          => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/lyrics"
                        ]
                    ],
                    "owners"          => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/owners"
                        ]
                    ],
                    "providers"       => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/providers"
                        ]
                    ],
                    "radio"           => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/radio"
                        ]
                    ],
                    "shares"          => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/shares"
                        ]
                    ],
                    "similarTracks"   => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/similarTracks"
                        ]
                    ],
                    "sourceFile"      => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/sourceFile"
                        ]
                    ],
                    "trackStatistics" => [
                        "links" => [
                            "self" => "/tracks/151799532/relationships/trackStatistics"
                        ]
                    ]
                ]
            ],
            "links" => [
                "self" => "/tracks/151799532"
            ]
        ];
        $trackArtistsTwo = [
            "data"  => [
                [
                    "id"   => "3652822",
                    "type" => "artists"
                ],
                [
                    "id"   => "17548",
                    "type" => "artists"
                ],
                [
                    "id"   => "4006106",
                    "type" => "artists"
                ]
            ],
            "links" => [
                "self" => "/tracks/151799532/relationships/artists"
            ]
        ];
        $artistTwo = [
            "data"  => [
                "id"            => "3652822",
                "type"          => "artists",
                "attributes"    => [
                    "name"          => "J. Cole",
                    "popularity"    => 0.9410301546416101,
                    "externalLinks" => [
                        [
                            "href" => "https://twitter.com/JColeNC",
                            "meta" => [
                                "type" => "TWITTER"
                            ]
                        ],
                        [
                            "href" => "https://tidal.com/browse/artist/3652822",
                            "meta" => [
                                "type" => "TIDAL_SHARING"
                            ]
                        ]
                    ]
                ],
                "relationships" => [
                    "albums"         => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/albums"
                        ]
                    ],
                    "biography"      => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/biography"
                        ]
                    ],
                    "followers"      => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/followers"
                        ]
                    ],
                    "following"      => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/following"
                        ]
                    ],
                    "owners"         => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/owners"
                        ]
                    ],
                    "profileArt"     => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/profileArt"
                        ]
                    ],
                    "radio"          => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/radio"
                        ]
                    ],
                    "roles"          => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/roles"
                        ]
                    ],
                    "similarArtists" => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/similarArtists"
                        ]
                    ],
                    "trackProviders" => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/trackProviders"
                        ]
                    ],
                    "tracks"         => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/tracks"
                        ]
                    ],
                    "videos"         => [
                        "links" => [
                            "self" => "/artists/3652822/relationships/videos"
                        ]
                    ]
                ]
            ],
            "links" => [
                "self" => "/artists/3652822"
            ]
        ];
        $playlistTracksResponse = [
            "data"  => [
                [
                    "id"   => "37704290",
                    "type" => "tracks",
                    "meta" => [
                        "itemId"  => "2b3d2f54-ac47-4d9e-b61e-5552b77bc981",
                        "addedAt" => "2025-11-29T22:10:10.701001Z"
                    ]
                ],
                [
                    "id"   => "151799532",
                    "type" => "tracks",
                    "meta" => [
                        "itemId"  => "38a30cb3-2312-4b6a-b80e-331924dbac22",
                        "addedAt" => "2025-11-29T22:10:18.057119Z"
                    ]
                ]
            ],
            "links" => [
                "self" => "/playlists/8f95326f-17c8-4c1d-bbd8-9364df0cad7b/relationships/items"
            ]
        ];

        Http::fake([
            TidalService::BASE_URL . '/playlists*/relationships/items' => Http::response($playlistTracksResponse),
            TidalService::BASE_URL . '/tracks/37704290'                => Http::response($trackOne),
            TidalService::BASE_URL . '/tracks/151799532'               => Http::response($songTwo),
            TidalService::BASE_URL . '/tracks/*/relationships/artists' => Http::sequence([
                Http::response($trackArtistsOne),
                Http::response($trackArtistsTwo),
            ]),
            TidalService::BASE_URL . '/artists/*'                      => Http::sequence([
                Http::response($artistOne),
                Http::response($artistTwo),
            ]),
        ]);

        $playlistTracks = (new TidalService($this->oac))->getPlaylistTracks('some-bunk-id');

        collect($playlistTracks)->each(fn($t) => $this->assertInstanceOf(Track::class, $t));

        $this->assertEquals("Empire State Of Mind", $playlistTracks[0]->name);
        $this->assertEquals("New York Times", $playlistTracks[1]->name);
        $this->assertEquals(["JAY Z"], $playlistTracks[0]->artists);
        $this->assertEquals(["J. Cole"], $playlistTracks[1]->artists);
    }

    public function test_it_returns_playlist_id_on_successful_creation()
    {
        $expectedPlaylistId = "a2c4476a-97a7-4394-a0dc-ea8744f82f21";
        Http::fake([
            TidalService::BASE_URL . '/playlists' => Http::response([
                "data"  => [
                    "id"            => $expectedPlaylistId,
                    "type"          => "playlists",
                    "attributes"    => [
                        "name"           => "8f95326f-17c8-4c1d-bbd8-9364df0cad7b",
                        "description"    => "",
                        "bounded"        => false,
                        "externalLinks"  => [
                            [
                                "href" => "https://listen.tidal.com/playlist/a2c4476a-97a7-4394-a0dc-ea8744f82f21",
                                "meta" => [
                                    "type" => "TIDAL_SHARING"
                                ]
                            ],
                            [
                                "href" => "https://tidal.com/playlist/a2c4476a-97a7-4394-a0dc-ea8744f82f21?play=true",
                                "meta" => [
                                    "type" => "TIDAL_AUTOPLAY_ANDROID"
                                ]
                            ],
                            [
                                "href" => "https://tidal.com/playlist/a2c4476a-97a7-4394-a0dc-ea8744f82f21?play=true",
                                "meta" => [
                                    "type" => "TIDAL_AUTOPLAY_IOS"
                                ]
                            ],
                            [
                                "href" => "https://listen.tidal.com/playlist/a2c4476a-97a7-4394-a0dc-ea8744f82f21?play=true",
                                "meta" => [
                                    "type" => "TIDAL_AUTOPLAY_WEB"
                                ]
                            ]
                        ],
                        "createdAt"      => "2025-12-02T22:23:27.217Z",
                        "lastModifiedAt" => "2025-12-02T22:23:27.217Z",
                        "accessType"     => "UNLISTED",
                        "playlistType"   => "USER"
                    ],
                    "relationships" => [
                        "coverArt" => [
                            "links" => [
                                "self" => "/playlists/a2c4476a-97a7-4394-a0dc-ea8744f82f21/relationships/coverArt"
                            ]
                        ],
                        "items"    => [
                            "links" => [
                                "self" => "/playlists/a2c4476a-97a7-4394-a0dc-ea8744f82f21/relationships/items"
                            ]
                        ],
                        "owners"   => [
                            "links" => [
                                "self" => "/playlists/a2c4476a-97a7-4394-a0dc-ea8744f82f21/relationships/owners"
                            ]
                        ]
                    ]
                ],
                "links" => [
                    "self" => "/playlists/a2c4476a-97a7-4394-a0dc-ea8744f82f21"
                ]
            ])
        ]);

        $id = (new TidalService($this->oac))->createPlaylist('some-bunk-id');

        $this->assertEquals($expectedPlaylistId, $id);
    }

    public function test_it_returns_false_if_playlist_creation_fails()
    {
        Http::fake([TidalService::BASE_URL . '/playlists' => Http::response([], 422)]);

        $result = (new TidalService($this->oac))->createPlaylist('some-bunk-id');

        $this->assertFalse($result);
    }

    public function test_it_maps_search_results_to_song_dto()
    {
        Http::fake([TidalService::BASE_URL . '/searchResults*' => Http::response([
            "data"     => [
                "attributes"    => [
                    "trackingId" => "ee0d24af-a261-4c1b-9e54-d3457724d9e3"
                ],
                "id"            => "Kanye%20West%20Yikes",
                "relationships" => [
                    "albums"    => [
                        "links" => [
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/albums?countryCode=US"
                        ]
                    ],
                    "artists"   => [
                        "links" => [
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/artists?countryCode=US"
                        ]
                    ],
                    "playlists" => [
                        "links" => [
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/playlists?countryCode=US"
                        ]
                    ],
                    "topHits"   => [
                        "links" => [
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/topHits?countryCode=US"
                        ]
                    ],
                    "tracks"    => [
                        "data"  => [
                            [
                                "id"   => "98156345",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "4875684",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "20753867",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57317924",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273419",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273411",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57317920",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273420",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273417",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "20753864",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273414",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273415",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "92099364",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "57273413",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "98156350",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "98156346",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "98156348",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "20753858",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "199142355",
                                "type" => "tracks"
                            ],
                            [
                                "id"   => "121012115",
                                "type" => "tracks"
                            ]
                        ],
                        "links" => [
                            "meta" => [
                                "nextCursor" => "3nI1Esi"
                            ],
                            "next" => "/searchResults/Kanye%20West%20Yikes/relationships/tracks?countryCode=US&page%5Bcursor%5D=3nI1Esi",
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/tracks?countryCode=US"
                        ]
                    ],
                    "videos"    => [
                        "links" => [
                            "self" => "/searchResults/Kanye%20West%20Yikes/relationships/videos?countryCode=US"
                        ]
                    ]
                ],
                "type"          => "searchResults"
            ],
            "included" => [
                [
                    "attributes"    => [
                        "accessType"    => "PUBLIC",
                        "availability"  => [
                            "STREAM",
                            "DJ"
                        ],
                        "copyright"     => [
                            "text" => "\u2117 2018 Getting Out Our Dreams II, LLC, distributed by Def Jam, a division of UMG Recordings, Inc., 1755 Broadway, New York, New York 10019."
                        ],
                        "createdAt"     => "2018-11-06T23:21:13Z",
                        "duration"      => "PT3M9S",
                        "explicit"      => true,
                        "externalLinks" => [
                            [
                                "href" => "https://tidal.com/browse/track/98156345",
                                "meta" => [
                                    "type" => "TIDAL_SHARING"
                                ]
                            ]
                        ],
                        "isrc"          => "USUM71807679",
                        "mediaTags"     => [
                            "HIRES_LOSSLESS",
                            "LOSSLESS"
                        ],
                        "popularity"    => 0.789001818624165,
                        "spotlighted"   => false,
                        "title"         => "Yikes",
                        "version"       => null
                    ],
                    "id"            => "98156345",
                    "relationships" => [
                        "albums"          => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/albums?countryCode=CA"
                            ]
                        ],
                        "artists"         => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/artists?countryCode=CA"
                            ]
                        ],
                        "genres"          => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/genres?countryCode=CA"
                            ]
                        ],
                        "lyrics"          => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/lyrics?countryCode=CA"
                            ]
                        ],
                        "owners"          => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/owners?countryCode=CA"
                            ]
                        ],
                        "providers"       => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/providers?countryCode=CA"
                            ]
                        ],
                        "radio"           => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/radio?countryCode=CA"
                            ]
                        ],
                        "shares"          => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/shares?countryCode=CA"
                            ]
                        ],
                        "similarTracks"   => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/similarTracks?countryCode=CA"
                            ]
                        ],
                        "sourceFile"      => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/sourceFile?countryCode=CA"
                            ]
                        ],
                        "trackStatistics" => [
                            "links" => [
                                "self" => "/tracks/98156345/relationships/trackStatistics?countryCode=CA"
                            ]
                        ]
                    ],
                    "type"          => "tracks"
                ]
            ],
            "links"    => [
                "self" => "/searchResults/Kanye%20West%20Yikes?include=tracks&countryCode=US"
            ]
        ])]);

        $candidates = (new TidalService($this->oac))->searchTrack(
            new Track([
                'name'    => 'Yikes',
                'artists' => ['Kanye West'],
            ])
        );

        $this->assertCount(1, $candidates);
        $this->assertInstanceOf(Track::class, $candidates[0]);

        $candidate = $candidates[0];

        $this->assertEquals(TidalService::PROVIDER, $candidate->source);
        $this->assertEquals('98156345', $candidate->remote_id);
        $this->assertEquals("Yikes", $candidate->name);
        $this->assertEquals(
            "/tracks/98156345/relationships/artists?countryCode=CA",
            Arr::get($candidate->meta, 'primaryArtistLink')
        );
    }

    public function test_it_returns_true_if_track_added_to_playlist()
    {
        Http::fake([TidalService::BASE_URL . "/playlists/*" => Http::response()]);

        $this->assertTrue((new TidalService($this->oac))->addTrackToPlaylist(
            'some-id',
            new Track([
                'name'    => 'Yikes',
                'artists' => ['Kanye West'],
            ])
        ));
    }

    public function test_it_returns_false_if_track_not_added_to_playlist()
    {
        Http::fake([TidalService::BASE_URL . "/playlists/*" => Http::response([], 422)]);

        $this->assertFalse((new TidalService($this->oac))->addTrackToPlaylist(
            'some-id',
            new Track([
                'name'    => 'Yikes',
                'artists' => ['Kanye West'],
            ])
        ));
    }

    public function test_it_fills_artist_info_when_required()
    {
        $primaryArtistResponse = [
            "data"  => [
                ["id" => "25022", "type" => "artists"]],
            "links" => ["self" => "/tracks/98156345/relationships/artists?countryCode=CA"]
        ];

        $artistDataResponse = [
            "data"  => [
                "id"            => "25022",
                "type"          => "artists",
                "attributes"    => [
                    "name"          => "Kanye West",
                    "popularity"    => 0.968152427682656,
                    "externalLinks" => [
                        [
                            "href" => "https://instagram.com/ye",
                            "meta" => [
                                "type" => "INSTAGRAM"
                            ]
                        ],
                        [
                            "href" => "https://yeezy.com/",
                            "meta" => [
                                "type" => "OFFICIAL_HOMEPAGE"
                            ]
                        ],
                        [
                            "href" => "https://twitter.com/kanyewest",
                            "meta" => [
                                "type" => "TWITTER"
                            ]
                        ],
                        [
                            "href" => "https://tidal.com/browse/artist/25022",
                            "meta" => [
                                "type" => "TIDAL_SHARING"
                            ]
                        ]
                    ]
                ],
                "relationships" => [
                    "albums"         => [
                        "links" => [
                            "self" => "/artists/25022/relationships/albums"
                        ]
                    ],
                    "biography"      => [
                        "links" => [
                            "self" => "/artists/25022/relationships/biography"
                        ]
                    ],
                    "followers"      => [
                        "links" => [
                            "self" => "/artists/25022/relationships/followers"
                        ]
                    ],
                    "following"      => [
                        "links" => [
                            "self" => "/artists/25022/relationships/following"
                        ]
                    ],
                    "owners"         => [
                        "links" => [
                            "self" => "/artists/25022/relationships/owners"
                        ]
                    ],
                    "profileArt"     => [
                        "links" => [
                            "self" => "/artists/25022/relationships/profileArt"
                        ]
                    ],
                    "radio"          => [
                        "links" => [
                            "self" => "/artists/25022/relationships/radio"
                        ]
                    ],
                    "roles"          => [
                        "links" => [
                            "self" => "/artists/25022/relationships/roles"
                        ]
                    ],
                    "similarArtists" => [
                        "links" => [
                            "self" => "/artists/25022/relationships/similarArtists"
                        ]
                    ],
                    "trackProviders" => [
                        "links" => [
                            "self" => "/artists/25022/relationships/trackProviders"
                        ]
                    ],
                    "tracks"         => [
                        "links" => [
                            "self" => "/artists/25022/relationships/tracks"
                        ]
                    ],
                    "videos"         => [
                        "links" => [
                            "self" => "/artists/25022/relationships/videos"
                        ]
                    ]
                ]
            ],
            "links" => [
                "self" => "/artists/25022"
            ]
        ];

        Http::fake([
            TidalService::BASE_URL . '/tracks/98156345/relationships/artists?countryCode=CA' => Http::response($primaryArtistResponse),
            '*'                                                                              => Http::response($artistDataResponse, 200)
        ]);

        $track = (new TidalService($this->oac))->fillMissingInfo(
            new Track([
                'remote_id' => '98156345',
                'name'      => 'Yikes',
                'artists'   => ['Kanye West'],
                'meta'      => [
                    'primaryArtistLink' => "/tracks/98156345/relationships/artists?countryCode=CA"
                ]
            ])
        );

        $this->assertEquals("Yikes", $track->name);
        $this->assertCount(1, $track->artists);
        $this->assertEquals("Kanye West", $track->artists[0]);
    }
}
